[tool.black]
line-length = 100
target_version = ['py312']
skip-magic-trailing-comma = true

[tool.mypy]
cache_fine_grained = true
local_partial_types = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
strict_optional = false
plugins = ["numpy.typing.mypy_plugin"]
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true
disable_error_code = "annotation-unchecked"

[[tool.mypy.overrides]]
module = [
    "stim.*",
    "stimcirq.*",
    "sympy.*",
    "pygltflib.*",
]
follow_imports = "silent"
ignore_missing_imports = true

[tool.pylint.messages_control]
max-line-length = 100
disable = [ "all" ]
enable = [
    "abstract-class-instantiated",
    "assignment-from-no-return",
    "bad-chained-comparison",
    "bad-mcs-classmethod-argument",
    "bad-mcs-method-argument",
    "bad-option-value",
    "bad-reversed-sequence",
    "bad-super-call",
    "deprecated-decorator",
    "duplicate-argument-name",
    "method-hidden",
    "no-value-for-parameter",
    "nonexistent-operator",
    "raising-bad-type",
    "raising-format-tuple",
    "redefined-slots-in-subclass",
    "self-cls-assignment",
    "shadowed-import",
    "simplifiable-condition",
    "simplifiable-if-statement",
    "unexpected-keyword-arg",
    "unneeded-not",
    "unreachable",
    "unrecognized-inline-option",
    "use-maxsplit-arg",
    "using-constant-test",
]

[tool.ruff]
line-length = 100
preview = true
lint.select = [
    "N804",
    "N804",
    "PLE1310",
    "B005",
    "PLR0124",
    "PLR1701",
    "PLR1711",
    "PLR1730",
    "B012",
    "PLE0116",
    "B006",
    "F601",
    "F602",
    "B033",
    "D419",
    "B018",
    "F541",
    "F811",
    "PLW0406",
    "PLE0100",
    "E501",
    "B002",
    "B012",
    "RET508",
    "RET507",
    "F901",
    "F701",
    "F702",
    "B018",
    "B018",
    "B018",
    "PLR0206",
    "A001",
    "A002",
    "PLE0101",
    "F706",
    "E711",
    "E712",
    "E999",
    "F821",
    "PIE790",
    "PLE0302",
    "PLR1733",
    "PLR1736",
    "F841",
    "F405",
    "PLW0120",
    "F403",
    "C4",
    "E402",
    "F632",
    "F704",
    "FURB101",
    "FURB103",
    "FURB105",
    "FURB116",
    "FURB131",
    "FURB132",
    "FURB136",
    "FURB142",
    "FURB145",
    "FURB148",
    "FURB166",
    "FURB167",
    "FURB168",
    "FURB169",
    "FURB171",
    "FURB192",
    "ISC",
    "N805",
    "PERF101",
    "PERF102",
    "PERF402",
    "PERF403",
    "PLW0245",
    "PLW1501",
    "RUF005",
    "RUF013",
    "RUF015",
    "RUF019",
    "RUF027",
    "RUF100",
    "RUF200",
    "SIM103",
    "SIM110",
    "SIM113",
    "SIM115",
    "SIM116",
    "SIM201",
    "SIM202",
    "SIM208",
    "SIM210",
    "SIM211",
    "SIM222",
    "SIM223",
    "SIM401",
    "TID251",
    "UP004",
    "UP006",
    "UP008",
    "UP010",
    "UP018",
    "UP027",
    "UP028",
    "UP034",
    "UP035",
    "UP037",
    "W605",
    "PLE1205",
    "PLE1206",
    "NPY201",
]
